import KeyNudge from "../components/KeyNudge.jsx";

export default function ReportScreen({ ds, apiKey, setPage, narrativeText, narrativeLoading, generateNarrative, narrativeAbortRef }) {
  return (
    <div style={{ maxWidth: "760px", margin: "0 auto", animation: "fadeSlide 0.3s ease" }}>
      <div style={{ marginBottom: "24px" }}>
        <h2 style={{ fontFamily: "'Syne', sans-serif", fontSize: "20px", fontWeight: 800, marginBottom: "8px" }}>Report</h2>
        <p style={{ color: "#8892b0", fontSize: "13px" }}>LUMIQ generates executive-grade decision briefs via Groq — your data becomes a story that drives action.</p>
      </div>
      <div style={{ display: "flex", gap: "10px", marginBottom: "20px", alignItems: "center", flexWrap: "wrap" }}>
        <button className="btn-primary" onClick={generateNarrative} disabled={narrativeLoading || !ds || !apiKey || apiKey === "demo"}>{narrativeLoading ? "Oracle is writing..." : "Generate Decision Brief"}</button>
        {narrativeLoading && apiKey && apiKey !== "demo" && (
          <button className="btn-ghost" onClick={() => narrativeAbortRef.current?.abort()}>⏹ Stop</button>
        )}
        {(!apiKey || apiKey === "demo") && <KeyNudge setPage={setPage} />}
      </div>
      {!ds && <div style={{ color: "#FFB627", fontSize: "13px", marginBottom: "16px" }}>⚠ Select a dataset from the sidebar first</div>}
      {narrativeText && (
        <div>
          <div style={{ display: "flex", alignItems: "center", gap: "8px", marginBottom: "12px" }}>
            <span className="badge badge-gold">DECISION BRIEF</span>
            <span style={{ fontSize: "11px", color: "#3d4f7c", fontFamily: "'DM Mono', monospace" }}>{ds?.name} · Generated by Oracle via Groq</span>
          </div>
          <div className="narrative-box">{narrativeText}{narrativeLoading && <span style={{ animation: "blink 0.8s infinite", color: "#FFB627" }}>▋</span>}</div>
          <div style={{ marginTop: "16px", display: "flex", gap: "10px" }}>
            <button className="btn-ghost" onClick={() => navigator.clipboard?.writeText(narrativeText)}>Copy Brief</button>
            <button className="btn-ghost" onClick={generateNarrative}>Regenerate</button>
          </div>
        </div>
      )}
    </div>
  );
}
